#!/bin/tcsh

foreach scen (./../scenarios/da2/w_e*.map.scen ./../scenarios/da2/w_w*.map.scen)

set alg = `echo 7`
set numExtendedGoals = `echo 300`

foreach weight (1.50 2.00 3.00 4.00 5.00 6.00 7.00 8.00 9.00 10.00)

set x = `echo $scen | sed 's/.*\///g'`
set map = `echo $x | sed 's/.scen//'`
echo "ALG " $alg " weight " $weight " map " $map

./../bin/release/DSDWA -rtDPS ./../maps/da2/$map $scen $weight $numExtendedGoals >> DPS_RaceTrack_9-results.txt

end
#end
end
